DATA_FEATURE_SET1="/home/long/long/datn-feast/data/data_df1.parquet"
DATA_FEATURE_SET2="/home/long/long/datn-feast/data/data_df2.parquet"
DATA_FEATURE_SET3="/home/long/long/datn-feast/data/data_df3.parquet"
DATA_FEATURE_SET4="/home/long/long/datn-feast/data/data_df4.parquet"
DATA_TARGET="/home/long/long/datn-feast/data/target_df.parquet"
